# Full URL to the pages
url: "https://vasyaod.github.io"

# Base path
basePath: "/my-tracks"

# Caption of the site.
siteTitle: "All My Bike Tracks"

# Header of the site
siteDescription: "Non-moderated collection of my bike and walking tracks which are updated every day automatically. More description of work principle you can find [here](https://github.com/vasyaod/my-trips-viewer/blob/master/how-my-tracks-works.md)"

